### ISSUE TITLE
Item spawn areas Y-Coords not working as intended

### ISSUE THREAD

**Issue by ItzMace** [ItzMace/LastMinerStanding-DEV#111]
@#202366211466461184

In 'playworld.yml' file, in 'Areas' section, if your Spawn areas 'Y coords' in 'From' section is higher or equal to 'Y coords' in 'To' section, chests won't spawn in those area.
i.e. (This one won't spawn chests.)

```
# This is Spawn Area #0:
      Spawn0:
        # How many items do you want to spawn in this area (eg. amount of Chests)
        AmountOfItems: 3
        # This is the start location of the item spawn area:
        From:
          X: 100
          Y: 68
          Z: -100
        # This is the end location of the item spawn area:
        To:
          X: 120
          Y: 64
          Z: -120
```

but if 'Y coords' in 'From' section is lower that 'Y coords' in 'To' section, chests will spawn.
(This one will spawn chests)

```
# This is Spawn Area #0:
      Spawn0:
        # How many items do you want to spawn in this area (eg. amount of Chests)
        AmountOfItems: 3
        # This is the start location of the item spawn area:
        From:
          X: 100
          Y: 64
          Z: -100
        # This is the end location of the item spawn area:
        To:
          X: 120
          Y: 68
          Z: -120
```

I haven't tested this problem on X and Z coords but I don't think it happens like Y coords.

***

don't forget that if it's higher or equal, the chest won't spawn. That means if Y coords are the same, (like 1 block tall spawn area) the chests won't spawn.
