### ISSUE TITLE
Give a custom displayname to items

### ISSUE THREAD

**Issue by ItzMace** [ItzMace/LastMinerStanding-DEV#127]
@#265168303427682306
```
    BOW:
      Weight: 8
      Chance: 5
       NAME: crosbow
```
